name: 'Require Reviewer'
description: 'Require a reviewer'
inputs:
  whom:  # comma list of reviewers required
    description: 'Comma separated list of reviewers'
    required: true
outputs:
  missing:
    description: 'Missing reviewers'
runs:
  using: 'node12'
  main: 'index.js'
