name: 'Require Reviewer'
description: 'Require a reviewer'
inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  whoms:  # comma list of reviewers required
    description: 'Comma separated list of reviewers'
    required: true
  skip:
    description: "Comma separated list of phrases that skip this action"
    required: false
outputs:
  missing:
    description: 'Missing reviewers'
runs:
  using: 'docker'
  image: 'Dockerfile'

