on: ['pull_request']
  # push:
  #   branches-ignore:
  #     - 'master'
  #     - 'main'

jobs:
  require_review:
    runs-on: ubuntu-latest
    name: Requires Review
    steps:
    - name: Check
      id: hello
      uses: remind101/action-require-reviewer@pull_request
      with:
        whoms: june-remind101,@empire-users
        GITHUB_TOKEN: env.AUTH_GITHUB_TOKEN
