on: ['pull_request','pull_request_review']
  # push:
  #   branches-ignore:
  #     - 'master'
  #     - 'main'

jobs:
  require_review:
    runs-on: ubuntu-latest
    name: Requires Review
    steps:
    - name: Check
      id: require_review
      uses: remind101/action-require-reviewer@pull_request
      with:
        whoms: june-remind101,@empire-users
        GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
